name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instala MySQL e drivers
      run: sudo apt install mysql-server mysql-client php-mysql -y

    - name: Cria um arquivo com a senha do administrador do banco
      run: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'admin';" > mysql-init

    - name: Cria um arquivo com a senha do administrador do banco
      run: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'admin';" > mysql-init

    - name: Altera a senha do usuário root
      run: sudo mysqld --init-file=/home/me/mysql-init &

    - name: Pára o MySQL server
      run: sudo service mysql stop   

    - name: Inicia o MySQL server
      run: sudo service mysql start      
 
    - name: Cria o banco de dados
      run: mysql -u root < data/acmezzio.sql

    - name: Instala dependências
      run: composer install

    - name: Inicia o servidor web
      run: php -S localhost:8000 -t public &

    - name: Executa os testes
      run: vendor/bin/phpunit
      
      

