name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instala MariaDB e drivers
      run:  sudo apt install mariadb-server mariadb-client -y
      
    - name: Pára o MariaDB server
      run: sudo service mariadb stop

    - name: Cria um arquivo com a senha do administrador do banco
      run: echo "ALTER USER root@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD(\"admin\");FLUSH PRIVILEGES;" > mysql-init

    - name: Altera a senha do usuário root
      run: sudo mysqld_safe --init-file=mysql-init &

    - name: Pára o MariaDB server
      run: sudo service mariadb stop

    - name: Inicia o MariaDB server
      run: sudo service mariadb start
 
    - name: Cria o banco de dados
      run: mysql -u root -p "admin" < data/acmezzio.sql

    - name: Instala dependências
      run: composer install

    - name: Inicia o servidor web
      run: php -S localhost:8000 -t public &

    - name: Executa os testes
      run: vendor/bin/phpunit
      
      

